language: node_js
node_js:
- "8"
branches:
  only:
  - master
before_script:
- npm install
script:
- gulp prod
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
cache:
  directories:
    - "node_modules"
